[workspace]
members = [
    "psst-protocol",
    "psst-core",
    "psst-cli",
    "psst-gui",
]

[profile.dev.package.symphonia]
opt-level = 2
[profile.dev.package.libsamplerate]
opt-level = 2

[patch.crates-io]
piet = { git = "https://github.com/jpochyla/piet", branch = "mac-gradients" }
piet-common = { git = "https://github.com/jpochyla/piet", branch = "mac-gradients" }
piet-coregraphics = { git = "https://github.com/jpochyla/piet", branch = "mac-gradients" }
