[package]
name = "psst-gui"
version = "0.1.0"
authors = ["Jan Pochyla <jpochyla@gmail.com>"]
edition = "2018"
build = "build.rs"
description = "Fast Spotify client with native GUI"
repository = "https://github.com/jpochyla/psst"

[dependencies]
psst-core = { path = "../psst-core" }

# Common
crossbeam-channel = { version = "0.5.2" }
env_logger = { version = "0.9.0" }
fs_extra = { version = "1.2.0" }
itertools = { version = "0.10.3" }
log = { version = "0.4.14" }
lru-cache = { version = "0.1.2" }
once_cell = { version = "1.10.0" }
parking_lot = { version = "0.12.0" }
platform-dirs = { version = "0.3.0" }
rand = { version = "0.8.5" }
regex = { version = "1.5.5" }
serde = { version = "1.0.136", features = ["derive", "rc"] }
serde_json = { version = "1.0.79" }
threadpool = { version = "1.8.1" }
time = { version = "0.3.7", features = ["macros", "formatting"] }
time-humanize = { version = "0.1.3" }
ureq = { version = "2.4.0", features = ["json", "socks-proxy"] }
url = { version = "2.2.2" }

# GUI
druid = { git = "https://github.com/jpochyla/druid", branch = "psst", features = ["im", "image", "jpeg", "png", "serde"] }
druid-enums = { git = "https://github.com/luleyleo/druid-enums" }
druid-shell = { git = "https://github.com/jpochyla/druid", branch = "psst", features = ["raw-win-handle"] }
open = { version = "2.1.1" }
raw-window-handle = { version = "0.3.3" }  # Needs to be compatible with what druid is using.
souvlaki = { version = "0.5.1" }

[target.'cfg(windows)'.build-dependencies]
winres = { version = "0.1.12" }

[package.metadata.bundle]
name = "Psst"
identifier = "com.jpochyla.psst"
icon = [
    "assets/logo_32.png",
    "assets/logo_64.png",
    "assets/logo_128.png",
    "assets/logo_256.png",
    "assets/logo_512.png",
]
version = "0.1.0"
resources = []
copyright = "Copyright (c) Jan Pochyla 2021. All rights reserved."
category = "Music"
short_description = "Fast Spotify client with native GUI"
long_description = """
Small and efficient graphical music player for Spotify network.
"""
