[package]
name = "psst-gui"
version = "0.1.0"
authors = ["Jan Pochyla <jpochyla@gmail.com>"]
edition = "2018"

[dependencies]
psst-core = { path = "../psst-core" }

chrono = { version = "0.4", features = ["serde"] }
crossbeam-channel = "0.5"
druid-shell = { git = "https://github.com/linebender/druid", features = ["raw-win-handle"] }
druid = { git = "https://github.com/linebender/druid", features = ["im", "image", "jpeg", "png", "serde"] }
env_logger = "0.8"
fs_extra = "1.2"
itertools = "0.10"
log = "0.4"
lru-cache = "0.1"
once_cell = "1.7"
open = "1.6"
platform-dirs = "0.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
souvlaki = { git = "https://github.com/jpochyla/souvlaki", branch = "macos" }
ureq = { version = "2.1", features = ["json"] }